# Generated by Django 6.0 on 2025-12-31 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodylog',
            name='image_back',
            field=models.ImageField(blank=True, help_text='후면 사진', null=True, upload_to='body_images/%Y/%m/%d/back/'),
        ),
        migrations.AddField(
            model_name='bodylog',
            name='image_front',
            field=models.ImageField(blank=True, help_text='정면 사진', null=True, upload_to='body_images/%Y/%m/%d/front/'),
        ),
        migrations.AddField(
            model_name='bodylog',
            name='image_side',
            field=models.ImageField(blank=True, help_text='측면 사진', null=True, upload_to='body_images/%Y/%m/%d/side/'),
        ),
        migrations.AlterField(
            model_name='bodylog',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='기록 날짜'),
        ),
        migrations.AlterField(
            model_name='bodylog',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='키 (cm)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodylog',
            name='note',
            field=models.TextField(blank=True, help_text='기타 메모', null=True),
        ),
        migrations.AlterField(
            model_name='bodylog',
            name='user',
            field=models.ForeignKey(help_text='기록을 소유한 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bodylog',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='몸무게 (kg)', max_digits=5),
        ),
    ]
