# Generated by Django 6.0 on 2026-01-01 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_bodylog_image_back_bodylog_image_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodylog',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='키 (cm)', max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='bodylog',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='몸무게 (kg)', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
