# Generated by Django 6.0 on 2026-01-01 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_bodylog_height_alter_bodylog_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodylog',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='몸무게 (kg)', max_digits=6, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
